FROM prom/prometheus
ADD prometheus.yml /etc/prometheus/
LABEL version="1.0.0" description="UploaderClient" maintainer="grupo 4"
RUN apt-get update -y
RUN apt-get install -y python-pip python-dev build-essential
RUN pip install flask
RUN pip install requests
EXPOSE 5001
EXPOSE 5000
COPY . /UploaderClient
WORKDIR /UploaderClient
ENTRYPOINT ["python"]
CMD ["app.py"]