FROM python:3
LABEL version="1.0.0" description="UploaderClient" maintainer="grupo 4"
RUN pip install flask
RUN pip install requests
EXPOSE 5001
EXPOSE 5000
COPY . /UploaderClient
WORKDIR /UploaderClient
ENTRYPOINT ["python"]
CMD ["app.py"]