global:
  scrape_interval:     15s
  evaluation_interval: 20s

scrape_configs:
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:

    - targets:
      - 192.168.2.101:8080
      - 192.168.2.100:8080
 
  - job_name: 'Virtual Machine'
    scrape_interval: 10s
    static_configs:
      
      - targets: ['192.168.2.100:9100']
        labels:
          service: 'VM 1'
      
      - targets: ['192.168.2.101:9100']
        labels:
          service: 'VM 2'
  
