FROM python:3
LABEL version="1.0.0" description="DockerDatabase" maintainer="grupo 4"
RUN pip install flask
RUN pip install requests
RUN pip install pymongo
EXPOSE 27017
COPY . /DockerDatabase
WORKDIR /DockerDatabase
ENTRYPOINT ["python"]
CMD ["dockerDatabase.py"]