FROM python:3
LABEL version="1.0.0" description="UploaderServer" maintainer="grupo 4"
EXPOSE 5000
EXPOSE 5001
COPY . /UploaderServer
WORKDIR /UploaderServer
RUN pip install flask
RUN pip install requests
ENTRYPOINT ["python"]
CMD ["app.py"]