FROM ubuntu:latest
LABEL version="1.0.0" description="UploaderServer" maintainer="grupo 4"
RUN apt-get update -y
RUN apt-get install -y python-pip python-dev build-essential
EXPOSE 5000
EXPOSE 5001
COPY . /UploaderServer
WORKDIR /UploaderServer
RUN pip install flask
ENTRYPOINT ["python"]
CMD ["app.py"]